// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: leaderboard.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertLeaderboardSnapshot = `-- name: InsertLeaderboardSnapshot :one
INSERT INTO leaderboard_snapshots (
    time_window,
    generated_at,
    entries,
    source_hash
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING snapshot_id, time_window, generated_at, entries, source_hash, created_at
`

type InsertLeaderboardSnapshotParams struct {
	TimeWindow  string             `json:"time_window"`
	GeneratedAt pgtype.Timestamptz `json:"generated_at"`
	Entries     []byte             `json:"entries"`
	SourceHash  string             `json:"source_hash"`
}

func (q *Queries) InsertLeaderboardSnapshot(ctx context.Context, arg InsertLeaderboardSnapshotParams) (LeaderboardSnapshot, error) {
	row := q.db.QueryRow(ctx, insertLeaderboardSnapshot,
		arg.TimeWindow,
		arg.GeneratedAt,
		arg.Entries,
		arg.SourceHash,
	)
	var i LeaderboardSnapshot
	err := row.Scan(
		&i.SnapshotID,
		&i.TimeWindow,
		&i.GeneratedAt,
		&i.Entries,
		&i.SourceHash,
		&i.CreatedAt,
	)
	return i, err
}

const listRecentSnapshots = `-- name: ListRecentSnapshots :many
SELECT snapshot_id, time_window, generated_at, entries, source_hash, created_at
FROM leaderboard_snapshots
WHERE time_window = $1
ORDER BY generated_at DESC
LIMIT $2
`

type ListRecentSnapshotsParams struct {
	TimeWindow string `json:"time_window"`
	Limit      int32  `json:"limit"`
}

func (q *Queries) ListRecentSnapshots(ctx context.Context, arg ListRecentSnapshotsParams) ([]LeaderboardSnapshot, error) {
	rows, err := q.db.Query(ctx, listRecentSnapshots, arg.TimeWindow, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LeaderboardSnapshot
	for rows.Next() {
		var i LeaderboardSnapshot
		if err := rows.Scan(
			&i.SnapshotID,
			&i.TimeWindow,
			&i.GeneratedAt,
			&i.Entries,
			&i.SourceHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
