// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	AuditID    int64              `json:"audit_id"`
	ActorID    pgtype.UUID        `json:"actor_id"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	Action     string             `json:"action"`
	Payload    []byte             `json:"payload"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	TraceID    pgtype.UUID        `json:"trace_id"`
}

type LeaderboardSnapshot struct {
	SnapshotID  pgtype.UUID        `json:"snapshot_id"`
	TimeWindow  string             `json:"time_window"`
	GeneratedAt pgtype.Timestamptz `json:"generated_at"`
	Entries     []byte             `json:"entries"`
	SourceHash  string             `json:"source_hash"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Match struct {
	MatchID              pgtype.UUID        `json:"match_id"`
	Mode                 string             `json:"mode"`
	QuestionCount        int16              `json:"question_count"`
	PerQuestionSeconds   int16              `json:"per_question_seconds"`
	GlobalTimeoutSeconds int16              `json:"global_timeout_seconds"`
	SeedHash             string             `json:"seed_hash"`
	LeaderboardEligible  bool               `json:"leaderboard_eligible"`
	StartedAt            pgtype.Timestamptz `json:"started_at"`
	CompletedAt          pgtype.Timestamptz `json:"completed_at"`
	Status               string             `json:"status"`
	CreatedBy            pgtype.UUID        `json:"created_by"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	Metadata             []byte             `json:"metadata"`
}

type PlayerMatchState struct {
	MatchID        pgtype.UUID        `json:"match_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	IsGuest        bool               `json:"is_guest"`
	JoinedAt       pgtype.Timestamptz `json:"joined_at"`
	LeftAt         pgtype.Timestamptz `json:"left_at"`
	FinalScore     pgtype.Int4        `json:"final_score"`
	Status         string             `json:"status"`
	Accuracy       pgtype.Numeric     `json:"accuracy"`
	StreakBonusPct pgtype.Numeric     `json:"streak_bonus_pct"`
	Answers        []byte             `json:"answers"`
}

type Question struct {
	QuestionID    pgtype.UUID        `json:"question_id"`
	Source        string             `json:"source"`
	Prompt        string             `json:"prompt"`
	Options       []string           `json:"options"`
	CorrectAnswer string             `json:"correct_answer"`
	Metadata      []byte             `json:"metadata"`
	Verified      bool               `json:"verified"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	UserID       pgtype.UUID        `json:"user_id"`
	Email        pgtype.Text        `json:"email"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	DisplayName  string             `json:"display_name"`
	UserType     string             `json:"user_type"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	Metadata     []byte             `json:"metadata"`
}
