// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error)
	CreatePlayerMatchState(ctx context.Context, arg CreatePlayerMatchStateParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetMatchForSummary(ctx context.Context, matchID pgtype.UUID) (Match, error)
	GetPlayerStatesByMatch(ctx context.Context, matchID pgtype.UUID) ([]PlayerMatchState, error)
	GetQuestionPool(ctx context.Context, arg GetQuestionPoolParams) ([]Question, error)
	GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error)
	GetUserByID(ctx context.Context, userID pgtype.UUID) (User, error)
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	InsertLeaderboardSnapshot(ctx context.Context, arg InsertLeaderboardSnapshotParams) (LeaderboardSnapshot, error)
	InsertQuestion(ctx context.Context, arg InsertQuestionParams) (Question, error)
	ListAuditLogsForEntity(ctx context.Context, arg ListAuditLogsForEntityParams) ([]AuditLog, error)
	ListRecentSnapshots(ctx context.Context, arg ListRecentSnapshotsParams) ([]LeaderboardSnapshot, error)
	PromoteGuestToRegistered(ctx context.Context, arg PromoteGuestToRegisteredParams) (User, error)
	UpdateMatchStatus(ctx context.Context, arg UpdateMatchStatusParams) error
	UpdatePlayerMatchResult(ctx context.Context, arg UpdatePlayerMatchResultParams) error
	UpdateUserLogin(ctx context.Context, userID pgtype.UUID) error
	UpsertQuestionVerification(ctx context.Context, arg UpsertQuestionVerificationParams) (Question, error)
}

var _ Querier = (*Queries)(nil)
