// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    password_hash,
    display_name,
    user_type,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    COALESCE($5, '{}'::jsonb)
)
RETURNING user_id, email, password_hash, display_name, user_type, status, created_at, updated_at, last_login_at, metadata
`

type CreateUserParams struct {
	Email        pgtype.Text `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
	DisplayName  pgtype.Text `json:"display_name"`
	UserType     pgtype.Text `json:"user_type"`
	Metadata     interface{} `json:"metadata"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.UserType,
		arg.Metadata,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.UserType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.Metadata,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_id, email, password_hash, display_name, user_type, status, created_at, updated_at, last_login_at, metadata FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.UserType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.Metadata,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, email, password_hash, display_name, user_type, status, created_at, updated_at, last_login_at, metadata FROM users
WHERE user_id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, userID pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.UserType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.Metadata,
	)
	return i, err
}

const promoteGuestToRegistered = `-- name: PromoteGuestToRegistered :one
UPDATE users
SET email = $1,
    password_hash = $2,
    user_type = 'registered',
    updated_at = NOW()
WHERE user_id = $3
RETURNING user_id, email, password_hash, display_name, user_type, status, created_at, updated_at, last_login_at, metadata
`

type PromoteGuestToRegisteredParams struct {
	Email        pgtype.Text `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
	UserID       pgtype.UUID `json:"user_id"`
}

func (q *Queries) PromoteGuestToRegistered(ctx context.Context, arg PromoteGuestToRegisteredParams) (User, error) {
	row := q.db.QueryRow(ctx, promoteGuestToRegistered, arg.Email, arg.PasswordHash, arg.UserID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.UserType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.Metadata,
	)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users
SET password_hash = $1,
    updated_at = NOW()
WHERE user_id = $2
`

type UpdatePasswordParams struct {
	PasswordHash pgtype.Text `json:"password_hash"`
	UserID       pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.PasswordHash, arg.UserID)
	return err
}

const updateUserLogin = `-- name: UpdateUserLogin :exec
UPDATE users
SET last_login_at = NOW(),
    updated_at = NOW()
WHERE user_id = $1
`

func (q *Queries) UpdateUserLogin(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateUserLogin, userID)
	return err
}
